from turtle import *

def draw_head(center_x, center_y):
    up()
    goto(center_x, center_y)
    down()
    setheading(35)
    begin_fill()
    circle(-155, 72)
    fillcolor("#F5D142")
    
    up()
    goto(65, 125)
    down()
    setheading(305)
    circle(-155, 32)
    setheading(300)
    circle(-145, 22)
    forward(6)
    setheading(265)
    circle(-85, 75)
    
    up()
    goto(-85, -90)
    down()
    up()
    goto(-155, 115)
    down()
    setheading(245)
    circle(115, 38)
    right(12)
    forward(12)
    setheading(255)
    circle(85, 118)
    
    up()
    goto(-85, -90)
    down()
    setheading(15)
    up()
    goto(-155, 115)
    down()
    up()
    goto(center_x, center_y)
    down()
    end_fill()
    
    # up()
    # goto(-60, -95)
    # down()
    # pencolor("#D5AD0E")
    # fillcolor("#D5AD0E")
    # begin_fill()
    # setheading(-15)
    # circle(125, 28)
    # setheading(-150)
    # forward(32)
    # setheading(185)
    # circle(-22, 22)
    # setheading(148)
    # forward(32)
    # end_fill()

def draw_eyes():
    color("black","black")
    up()
    goto(-120, 35)
    down()
    begin_fill()
    setheading(5)
    circle(26)
    end_fill()
    
    color("white", "white")
    up()
    goto(-115, 58)
    down()
    begin_fill()
    setheading(5)
    circle(11)
    end_fill()
    
    color("black", "black")
    up()
    goto(35, 48)
    down()
    begin_fill()
    setheading(5)
    circle(26)
    end_fill()
    
    color("white", "white")
    up()
    goto(27, 70)
    down()
    begin_fill()
    setheading(5)
    circle(11)
    end_fill()

def draw_cheeks():
    color("#8C4614", "#FF4601")
    up()
    goto(-120, -60)
    down()
    begin_fill()
    setheading(5)
    circle(28)
    end_fill()
    
    color("#8C4614", "#FF4601")
    up()
    goto(63, -30)
    down()
    begin_fill()
    setheading(5)
    circle(28)
    end_fill()

def draw_nose():
    color("black", "black")
    up()
    goto(-50, 45)
    down()
    begin_fill()
    circle(8, steps=3)
    end_fill()

def draw_mouth():
    color("black", "#FF6AB5")
    up()
    goto(-20, 30)
    down()
    begin_fill()
    setheading(265)
    forward(65)
    circle(-12, 155)
    forward(60)
    up()
    goto(-48, 29)
    down()
    end_fill()
    
    color("#8C0101", "#8C0101")
    begin_fill()
    up()
    goto(-20, 30)
    down()
    up()
    goto(-24, -8)
    down()
    up()
    goto(-62, -11)
    down()
    up()
    goto(-70, 20)
    down()
    up()
    goto(-48, 29)
    down()
    up()
    goto(-20, 30)
    down()
    end_fill()
    
    # color("black","#F5D142")
    # up()
    # goto(-88, 23)
    # down()
    # begin_fill()
    # setheading(-30)
    # for _ in range(2):
    #     setheading(-30)
    #     circle(37, 75)
    # end_fill()
    
    # color("#8C0101", "#8C0101")
    # up()
    # goto(-62, -11)
    # down()
    # begin_fill()
    # setheading(45)
    # circle(-35, 60)
    # goto(-26, -8)
    # up()
    # goto(-28, -25)
    # down()
    # setheading(160)
    # circle(27, 75)
    # end_fill()

def draw_ears():
    color("black","#F5D142")
    up()
    goto(-150, 100)
    down()
    begin_fill()
    setheading(170)
    circle(-253, 53)
    right(125)
    circle(-253, 53)
    end_fill()
    
    color("black", "black")
    up()
    goto(-240, 200)
    down()
    begin_fill()
    setheading(147)
    circle(175, 28)
    left(125)
    circle(-234, 15)
    left(76)
    circle(320, 10)
    end_fill()
    
    color("black", "#F5D142")
    up()
    goto(40, 130)
    down()
    begin_fill()
    setheading(69)
    circle(-253, 53)
    right(125)
    circle(-253, 53)
    end_fill()
    
    color("black", "black")
    up()
    goto(170, 210)
    down()
    begin_fill()
    setheading(57)
    circle(175, 28)
    left(121)
    circle(234, 18)
    left(76)
    circle(-305, 10)
    end_fill()

def draw_lightning():
   
    color("black", "#FFD700") 
    

    up()
    goto(120,-30)
    down()
    begin_fill()
    setheading(300)
    forward(25)
    setheading(240)
    forward(15)
    setheading(300)
    forward(20)
    setheading(0)
    forward(15)
    setheading(60)
    forward(25)
    setheading(0)
    forward(15)
    setheading(300)
    forward(20)
    end_fill()
    
    up()
    goto(-180, -30)
    down()
    begin_fill()
    setheading(240)
    forward(25)
    setheading(180)
    forward(15)
    setheading(240)
    forward(20)
    setheading(300)
    forward(15)
    setheading(240)
    forward(25)
    setheading(300)
    forward(15)
    setheading(240)
    forward(20)
    end_fill()

def setup():
    pensize(2)
    hideturtle()
    speed(10)

def main():
    setup()
    draw_head(-145, 125)
    draw_eyes()
    draw_cheeks()
    draw_nose()
    draw_mouth()
    draw_ears()
    draw_lightning()  
    done()

if __name__ == '__main__':
    main()